const {createClient}=window.supabase;
const sb=createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);
const $=s=>document.querySelector(s);
let config={games:[],packages:[],settings:{}}, currentUser=null;
const labels={topup:'إضافة رصيد',purchase:'شراء من المحفظة',adjustment:'تعديل إداري'};
const sectionNames={shop:'الألعاب والباقات',wallet:'المحفظة والنقاط',track:'تتبع الطلب',support:'التواصل مع الدعم',chatapps:'تطبيقات الدردشة'};const sectionTargets={...sectionNames,topup:'wallet',order:'shop',games:'shop'};
function safeSectionUrl(v){const u=String(v||'').trim();return /^(https?:\/\/|\/|#)/i.test(u)?u:''}
function loadDynamicSections(rows){document.querySelectorAll('[data-custom-section],.custom-section-card').forEach(x=>x.remove());const grid=document.querySelector('.quick-sections-grid');const back=document.querySelector('#sectionBack');if(!grid||!back)return;(rows||[]).forEach(x=>{const key='custom-'+x.slug;sectionNames[key]=x.title;sectionTargets[key]=key;grid.insertAdjacentHTML('beforeend',`<a class="quick-section-card custom-section-card" data-custom-section href="#${key}"><span class="quick-icon">${esc(x.icon||'✦')}</span><strong>${esc(x.title)}</strong><small>${esc(x.description||'')}</small><b>دخول القسم ←</b></a>`);back.insertAdjacentHTML('afterend',`<section class="section custom-section" data-main-section="${key}" data-custom-section><div class="container"><div class="section-title"><div><label>قسم مستقل</label><h2>${esc(x.icon||'✦')} ${esc(x.title)}</h2></div><p>${esc(x.description||'')}</p></div><div class="panel custom-section-panel"><div class="custom-content">${esc(x.content||'')}</div></div></div></section>`)});}
window.addEventListener('popstate',()=>{const h=location.hash.slice(1),t=sectionTargets[h];openMainSection(t||null,false,t&&h!==t?h:'')});window.addEventListener('hashchange',()=>{const h=location.hash.slice(1),t=sectionTargets[h];openMainSection(t||null,false,t&&h!==t?h:'')});
function openMainSection(name,writeHash=true,subId=''){const inside=!!sectionNames[name];document.body.classList.toggle('inside-section',inside);document.querySelectorAll('[data-main-section]').forEach(x=>x.classList.toggle('section-hidden',!inside||x.dataset.mainSection!==name));$('#sectionHome')?.classList.toggle('section-hidden',inside);$('#sectionBack')?.classList.toggle('hidden',!inside);if($('#sectionHeading'))$('#sectionHeading').textContent=inside?sectionNames[name]:'';if(writeHash)history.pushState({},'',inside?'#'+name:location.pathname+location.search);if(inside){window.scrollTo({top:0,behavior:'smooth'});if(subId)setTimeout(()=>document.getElementById(subId)?.scrollIntoView({behavior:'smooth',block:'start'}),120)}else window.scrollTo({top:0,behavior:'smooth'})}
let toastTimer;function flashMessage(text,type='error'){const el=$('#siteToast');if(!el)return;el.textContent=text;el.className=`site-toast ${type}`;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.add('hidden'),2000)}function show(id,text,type=''){const el=$(id);if(!el)return;el.textContent=text;el.className=`alert ${type}`;el.classList.remove('hidden')}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function money(n,c){return c==='SYP'?`${Number(n||0).toLocaleString('ar-SY')} ل.س`:`${Number(n||0).toFixed(2)} $`}
function whatsappNumber(v){let n=String(v||'').replace(/\D/g,'');if(n.startsWith('00'))n=n.slice(2);if(n.startsWith('0'))n='963'+n.slice(1);else if(!n.startsWith('963'))n='963'+n;return n}
async function loadConfig(){const [s,g,p,sec]=await Promise.all([sb.from('settings').select('key,value'),sb.from('games').select('*').eq('visible',true).order('sort_order'),sb.from('packages').select('*,games!inner(visible)').eq('visible',true).eq('games.visible',true).order('sort_order'),sb.from('site_sections').select('*').eq('visible',true).order('sort_order').order('id')]);if(s.error||g.error||p.error||sec.error)throw new Error('تعذر تحميل بيانات الموقع');config={settings:Object.fromEntries((s.data||[]).map(x=>[x.key,x.value])),games:g.data||[],packages:p.data||[],sections:sec.data||[]};loadDynamicSections(config.sections);const x=config.settings;if($('#brandName'))$('#brandName').textContent=x.site_name||'Base Card';if($('#brandTagline'))$('#brandTagline').textContent=x.tagline||'';if($('#walletPaymentInfo'))$('#walletPaymentInfo').textContent=x.sham_cash||'سيتم عرض بيانات شام كاش هنا بعد ضبطها من لوحة الإدارة.';if(x.sham_cash_qr&&$('#paymentQr')&&$('#qrBox')){$('#paymentQr').src=x.sham_cash_qr;$('#qrBox').classList.remove('hidden')}const wa=whatsappNumber(x.support_whatsapp);if(wa&&$('#whatsappLink')){$('#whatsappLink').href=`https://wa.me/${wa}`;if($('#whatsappNumber'))$('#whatsappNumber').textContent=x.support_whatsapp||''}const grid=$('#gamesGrid');grid.innerHTML='';config.games.forEach(g=>grid.insertAdjacentHTML('beforeend',`<article class="game-card"><span class="badge">متوفر الآن</span><h3>${esc(g.icon)} ${esc(g.name)}</h3><p>${esc(g.description)}</p><a class="btn" href="#order" data-game="${g.id}">شحن ${esc(g.name)} ←</a><span class="emoji">${esc(g.icon)}</span></article>`));const gs=$('#gameId');gs.innerHTML='<option value="">اختر اللعبة</option>'+config.games.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('')}
async function loadUser(){const {data}=await sb.auth.getUser();currentUser=data.user||null;let isAdmin=false;if(currentUser){const pr=await sb.from('profiles').select('role').eq('id',currentUser.id).maybeSingle();isAdmin=pr.data?.role==='admin'}document.querySelectorAll('.admin-link').forEach(x=>x.classList.toggle('hidden',!isAdmin));if(currentUser){$('#googleLogin').classList.add('hidden');$('#userMenu').classList.remove('hidden');$('#userName').textContent=`مرحبًا ${currentUser.user_metadata?.full_name||currentUser.email||'بك'}`}else{$('#googleLogin').classList.remove('hidden');$('#userMenu').classList.add('hidden')}}
async function signIn(){const {error}=await sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.href.split('?')[0]}});if(error)show('#walletAlert','تعذر فتح تسجيل الدخول عبر Google: '+error.message,'error')}
$('#googleLogin').addEventListener('click',e=>{e.preventDefault();signIn()});$('#logoutUser').addEventListener('click',async()=>{await sb.auth.signOut();location.reload()});
function fillPackages(){const id=Number($('#gameId').value),grid=$('#packagesGrid'),hidden=$('#packageId');hidden.value='';if(!id){grid.innerHTML='<div class="packages-empty">اختر اللعبة أولًا</div>';return}const packs=config.packages.filter(p=>p.game_id===id);grid.innerHTML=packs.length?packs.map(p=>`<button type="button" class="package-card" data-package-id="${p.id}"><span class="package-icon">✦</span><span class="package-name">${esc(p.name)}</span><span class="package-price">${esc(p.price_amount??p.price)} ${p.currency==='SYP'?'ل.س جديدة':'$'}</span>${p.price_usd?`<span class="package-usd">$${Number(p.price_usd).toFixed(2)}</span>`:''}<span class="package-check">✓</span></button>`).join(''):'<div class="packages-empty">لا توجد باقات متاحة لهذه اللعبة</div>'}
$('#gameId').addEventListener('change',fillPackages);document.addEventListener('click',e=>{const p=e.target.closest('.package-card');if(p){$('#packageId').value=p.dataset.packageId;document.querySelectorAll('.package-card').forEach(x=>x.classList.toggle('selected',x===p))}const g=e.target.closest('[data-game]');if(g){$('#gameId').value=g.dataset.game;fillPackages();openMainSection('shop',true,'order')}});
const initialHash=location.hash.slice(1),initialTarget=sectionTargets[initialHash];openMainSection(initialTarget||null,false,initialTarget&&initialHash!==initialTarget?initialHash:'');Promise.all([loadConfig(),loadUser()]).catch(()=>show('#orderAlert','تعذر تحميل بيانات الموقع حاليًا','error'));
