/* KM Card categories: games, chat apps, Syriatel and MTN only */
(function(){
  const KM_URL='kmcard-proxy';
  const escKm=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const textKm=x=>String(x?.name||'')+' '+String(x?.category_name||'');
  const isTransfer=x=>/(mtn|syriatel|سيريتل|سيرياتل|سيريتيل|ام تي ان)/i.test(textKm(x));
  const isChat=x=>/(chat|whatsapp|telegram|messenger|live|دردشة|تطبيقات الدردشة|application shipping)/i.test(textKm(x));
  function addKmSections(){
    const grid=document.querySelector('.quick-sections-grid'), back=document.querySelector('#sectionBack');
    if(!grid||!back||document.querySelector('#chatapps'))return;
    const cards=[['kmGames','🎮','ألعاب KM Card','ألعاب KM Card المتاحة للشحن'],['chatapps','💬','تطبيقات الدردشة','اشحن تطبيقات الدردشة من واجهة مستقلة'],['kmTransfer','📱','تحويل الرصيد','تحويل رصيد سيريتل وMTN']];
    cards.forEach(([id,icon,title,desc])=>{grid.insertAdjacentHTML('beforeend',`<a class="quick-section-card" href="#${id}"><span class="quick-icon">${icon}</span><strong>${title}</strong><small>${desc}</small><b>دخول القسم ←</b></a>`);back.insertAdjacentHTML('afterend',`<section id="${id}" class="section" data-main-section="${id}"><div class="container"><div class="section-title"><div><label>KM Card</label><h2>${icon} ${title}</h2></div><p>${desc}</p></div><div id="${id}Grid" class="games-grid"><div class="panel">جارٍ تحميل المنتجات...</div></div></div></section>`)});
    sectionNames.kmGames='ألعاب KM Card';sectionNames.chatapps='تطبيقات الدردشة';sectionNames.kmTransfer='تحويل الرصيد';sectionTargets.kmGames='kmGames';sectionTargets.chatapps='chatapps';sectionTargets.kmTransfer='kmTransfer';
  }
  function card(p){const rate=Number(config?.settings?.usd_to_syp_rate||130),sell=(Number(p.price||0)*rate*1.14);return `<button class="game-card km-product" data-km-id="${Number(p.id)}"><div class="game-card-art">${isChat(p)?'💬':isTransfer(p)?'📱':'🎮'}</div><div class="game-card-body"><h3>${escKm(p.name)}</h3><p>${escKm(p.category_name||'')}</p><b>${sell.toFixed(0)} ل.س</b><small>اضغط للشراء</small></div></button>`}
  function render(id,items){const el=document.querySelector('#'+id+'Grid');if(!el)return;el.innerHTML=items.length?items.slice(0,120).map(card).join(''):'<div class="panel">لا توجد منتجات متاحة حاليًا.</div>';el.querySelectorAll('.km-product').forEach(b=>b.addEventListener('click',()=>{const p=window.__kmProducts.find(x=>Number(x.id)===Number(b.dataset.kmId));openKmOrder(p)}))}
  function openKmOrder(p){if(!p)return;const sectionNames0=sectionNames.kmApps;openMainSection('shop',true,'order');let panel=document.querySelector('#kmProviderPanel');if(!panel){const form=document.querySelector('#orderForm');if(!form)return;panel=document.createElement('div');panel.id='kmProviderPanel';panel.className='panel';form.parentNode.insertBefore(panel,form);}
    const params=Array.isArray(p.params)?p.params:[];const choices=Array.isArray(p.qty_values)?p.qty_values:null;const qty=choices?`<label>الباقة/القيمة<select id="kmQty">${choices.map(x=>`<option value="${escKm(x)}">${escKm(x)}</option>`).join('')}</select></label>`:`<label>الكمية<input id="kmQty" type="number" min="${p.qty_values?.min||1}" max="${p.qty_values?.max||''}" value="1"></label>`;panel.innerHTML=`<h3>شراء ${escKm(p.name)}</h3>${params.map((x,i)=>`<label>${escKm(x)}<input data-km-param="${i}" required></label>`).join('')}${qty}<button id="kmSubmit" class="btn" type="button">شراء وشحن تلقائي</button><p class="muted">سيُحسب السعر النهائي بهامش Base Card ويُخصم من محفظتك.</p>`;document.querySelector('#orderForm')?.classList.add('hidden');panel.querySelector('#kmSubmit').onclick=async()=>{const btn=panel.querySelector('#kmSubmit');btn.disabled=true;try{const vals={};panel.querySelectorAll('[data-km-param]').forEach((x,i)=>{const key=String(params[i]||'param'+i);vals[key]=x.value;if(i===0)vals.playerId=x.value});const r=await sb.functions.invoke(KM_URL,{body:{action:'order',product:p,qty:Number(panel.querySelector('#kmQty').value||1),params:vals}});if(r.error||r.data?.error)throw new Error(r.data?.error||r.error.message);flashMessage('تم إرسال طلب الشحن تلقائيًا بنجاح.','success');}catch(e){flashMessage(e.message||'تعذر تنفيذ الشحن')}finally{btn.disabled=false}}}
  async function loadKm(){try{const r=await sb.functions.invoke(KM_URL,{body:{action:'products'}});if(r.error||r.data?.error)throw new Error(r.data?.error||r.error.message);window.__kmProducts=r.data.products||[];render('kmGames',window.__kmProducts.filter(x=>!isChat(x)&&!isTransfer(x)));render('chatapps',window.__kmProducts.filter(isChat));render('kmTransfer',window.__kmProducts.filter(isTransfer));}catch(e){document.querySelectorAll('#kmGamesGrid,#chatappsGrid,#kmTransferGrid').forEach(x=>x.innerHTML='<div class="panel">الخدمة قيد التجهيز، حاول لاحقًا.</div>')}}
  document.addEventListener('DOMContentLoaded',()=>{addKmSections();loadKm()});
})();
