/* Base Card KM Card chat-app catalogue. Preview/payment validation only: never creates a provider order. */
(function(){
'use strict';
var PROXY='kmcard-proxy', RATE=130, MARGIN=1.14, MIN_MARGIN_SYP=60;
var $=function(s){return document.querySelector(s);};
var esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});};
var text=function(p){return [p&&p.name,p&&p.category_name,p&&p.parent_name,p&&p.category&&p.category.name,p&&p.parent&&p.parent.name].filter(Boolean).join(' ');};
var isTransfer=function(p){return /(^|[^a-z])(mtn|syriatel|سيريتل|سيرياتل)([^a-z]|$)/i.test(text(p))||Number(p&&p.id)===11||Number(p&&p.id)===4;};
var isChat=function(p){
  if(isTransfer(p)||!p||p.available===false)return false;
  var t=text(p), cat=String(p.category_name||p.parent_name||'').toLowerCase();
  if(/whatsapp.*(number|direct|guaranteed)|number whatsapp|حسابات|توثيق سناب|برمج|سحب الرواتب/i.test(t))return false;
  return Number(p.parent_id)===6 || /application shipping section|telegram|discord|chat|live|livo|migo|tango|yalla live|nimo|viber|imo|party|سما شات|شات|دردشة/i.test(cat+' '+t);
};
var state={products:[],chat:[],selected:null};
function parse(raw){var seen=[];function walk(v,d){if(d>8||v==null)return [];if(Array.isArray(v))return v.filter(function(x){return x&&typeof x==='object'&&x.id!=null;});if(typeof v!=='object'||seen.indexOf(v)>=0)return [];seen.push(v);var keys=['products','items','results','data','result','payload'];for(var i=0;i<keys.length;i++){if(v[keys[i]]!=null){var a=walk(v[keys[i]],d+1);if(a.length)return a;}}return [];}return walk(raw,0);}
function settingsPrices(){var raw=window.__baseSettings&&window.__baseSettings.km_sale_prices,map={};try{map=typeof raw==='string'?JSON.parse(raw||'{}'):(raw||{});}catch(e){}return map;}
function overridePrice(p,q){var map=settingsPrices(), keys=[String(p.id)+':'+String(q),String(p.id)+'_'+String(q),String(p.id)+'-'+String(q),String(p.id)];for(var i=0;i<keys.length;i++){var n=Number(map[keys[i]]);if(isFinite(n)&&n>=0)return n;}return null;}
function quantityInfo(p){var q=p&&p.qty_values;if(q&&typeof q==='object'&&!Array.isArray(q)){var min=Number(q.min),max=Number(q.max);return {variable:p.product_type==='amount'||isFinite(min)||isFinite(max),min:isFinite(min)&&min>0?min:1,max:isFinite(max)&&max>0?max:null};}return {variable:false,min:1,max:null};}
function price(p,q){var info=quantityInfo(p), qty=Number(q)||info.min||1, provider=Number(p.price)||0;
  if(info.variable)provider=provider*qty;
  var override=overridePrice(p,qty), sale=override==null?Math.max(provider*MARGIN,provider+MIN_MARGIN_SYP/RATE):override;
  return {providerUsd:provider,saleUsd:sale,saleSyp:sale*RATE};
}
function card(p){var b=quantityInfo(p), c=price(p,b.min);var detail=b.variable?'من '+b.min.toLocaleString('en-US')+' وحدة — الحد حسب بيانات المزود':'باقة ثابتة من KM Card';return '<button type="button" class="game-card km-group" data-km-id="'+Number(p.id)+'"><span class="badge">متوفر الآن</span><h3>💬 '+esc(p.name||'تطبيق دردشة')+'</h3><p>'+detail+'</p><span class="package-price">$'+c.saleUsd.toFixed(2)+' · '+Math.round(c.saleSyp).toLocaleString('ar-SY')+' ل.س جديدة</span><span class="btn">شراء '+esc(p.name||'الآن')+' ←</span></button>';}
function draw(){var el=$('#chatappsGrid');if(el)el.innerHTML=state.chat.length?state.chat.map(card).join(''):'<div class="panel km-status error">لم يعثر مزود الخدمة على تطبيقات دردشة متاحة حاليًا.</div>';}
function inlineError(panel,msg){var x=panel.querySelector('.km-inline-error');if(!x){x=document.createElement('div');x.className='alert error km-inline-error';panel.appendChild(x);}x.textContent=msg;}
function render(p){state.selected=p;var b=quantityInfo(p), panel=$('#kmProviderPanel');if(!panel)return;var qhtml=b.variable?'<label class="full">الكمية المطلوبة (الحد الأدنى '+b.min.toLocaleString('en-US')+(b.max?'، الحد الأقصى '+b.max.toLocaleString('en-US'):'')+')<input id="kmQty" type="number" min="'+b.min+'" '+(b.max?'max="'+b.max+'"':'')+' step="1" value="'+b.min+'" inputmode="numeric" required></label>':'<div class="alert">باقة ثابتة: '+esc(p.name||'')+' — لا يمكن تغيير الكمية.</div>';
  var params=(Array.isArray(p.params)?p.params:[]).map(function(x,i){return '<label class="full">'+esc(x)+'<input data-km-param="'+i+'" required></label>';}).join('');
  panel.innerHTML='<h3>💬 شراء '+esc(p.name||'تطبيق الدردشة')+'</h3><p class="muted">تفاصيل المنتج والحدود مأخوذة مباشرة من KM Card. لن يتم إنشاء طلب حقيقي من هذه الواجهة.</p>'+params+qhtml+'<div id="kmLivePrice" class="price-note"></div><button id="kmPurchase" class="btn" type="button">متابعة الدفع من المحفظة ←</button><p class="muted">وضع الاختبار: زر الدفع يتحقق فقط ولا يخصم رصيدًا.</p>';
  var qty=$('#kmQty'), update=function(){var q=b.variable?Number(qty&&qty.value||0):1,c=price(p,q);$('#kmLivePrice').innerHTML='سعر المزود: $'+c.providerUsd.toFixed(4)+'<br><strong>سعر البيع: $'+c.saleUsd.toFixed(2)+' · '+Math.round(c.saleSyp).toLocaleString('ar-SY')+' ل.س جديدة</strong>';};
  if(qty)qty.addEventListener('input',update);update();$('#kmPurchase').onclick=function(){preview(p,panel);};
}
async function preview(p,panel){var b=quantityInfo(p),qty=b.variable?Number($('#kmQty')&&$('#kmQty').value||0):1;if(b.variable&&(!isFinite(qty)||!Number.isInteger(qty)||qty<b.min||(b.max&&qty>b.max)))return inlineError(panel,b.max?'الكمية يجب أن تكون عددًا صحيحًا بين '+b.min.toLocaleString('en-US')+' و'+b.max.toLocaleString('en-US')+'.':'الكمية يجب ألا تقل عن '+b.min.toLocaleString('en-US')+'.');for(var i=0;i<panel.querySelectorAll('[data-km-param]').length;i++){var x=panel.querySelectorAll('[data-km-param]')[i];if(!x.value.trim())return inlineError(panel,'أدخل '+(x.previousElementSibling?x.previousElementSibling.textContent:'البيانات المطلوبة')+' أولًا.');}var btn=$('#kmPurchase');btn.disabled=true;btn.textContent='جارٍ التحقق...';try{if(!window.sb||!sb.auth)throw Error('سجّل الدخول عبر Google أولًا قبل الشراء.');var au=await sb.auth.getUser();if(!au||!au.data||!au.data.user)throw Error('سجّل الدخول عبر Google أولًا قبل الشراء.');var w=await sb.from('wallets').select('balance_usd,balance_syp').eq('user_id',au.data.user.id).maybeSingle();if(w.error)throw Error('تعذر قراءة رصيد المحفظة حاليًا.');var c=price(p,qty),balance=Number(w.data&&w.data.balance_usd||0);if(balance+1e-9<c.saleUsd)throw Error('الرصيد غير كافٍ. السعر المطلوب $'+c.saleUsd.toFixed(2)+' ورصيدك $'+balance.toFixed(2)+'.');panel.querySelector('.km-inline-error')&&panel.querySelector('.km-inline-error').remove();panel.insertAdjacentHTML('beforeend','<div class="alert success">تم التحقق من الرصيد. لم يُنشأ طلب فعلي في وضع الاختبار.</div>');}catch(e){inlineError(panel,e.message||'تعذر التحقق من الدفع.');}finally{btn.disabled=false;btn.textContent='متابعة الدفع من المحفظة ←';}}
async function load(){var el=$('#chatappsGrid');if(el)el.innerHTML='<div class="panel km-status">جارٍ تحميل التطبيقات من KM Card...</div>';try{var list=[];if(window.sb&&sb.functions&&sb.functions.invoke){var r=await sb.functions.invoke(PROXY,{body:{action:'products'}});if(!r.error)list=parse(r.data).filter(function(p){return p&&p.available!==false&&p.id!=null;});}if(!list.length){var fallback=await fetch('./km-products.json?v=3',{cache:'no-store'});if(fallback.ok)list=(await fallback.json()).filter(function(p){return p&&p.available!==false&&p.id!=null;});}if(!list.length)throw Error('لم تصل منتجات KM Card');state.products=list;state.chat=list.filter(isChat);window.__kmProducts=list;draw();}catch(e){if(el)el.innerHTML='<div class="panel km-status error"><strong>تعذر تحميل منتجات KM Card</strong><br>'+esc(e.message||'حاول لاحقًا')+'</div>';}}
function open(p){var panel=$('#kmProviderPanel');if(!panel){panel=document.createElement('div');panel.id='kmProviderPanel';panel.className='panel';var order=document.querySelector('#order .container');if(order)order.insertBefore(panel,order.firstChild);else{var form=$('#orderForm');if(form)form.parentNode.insertBefore(panel,form);}}panel.classList.remove('hidden');if(typeof openMainSection==='function')openMainSection('order',true);else location.hash='order';setTimeout(function(){render(p);panel.scrollIntoView({behavior:'smooth',block:'start'});},80);}
document.addEventListener('click',function(e){var g=e.target.closest&&e.target.closest('.km-group');if(!g)return;e.preventDefault();var p=state.products.find(function(x){return Number(x.id)===Number(g.dataset.kmId);});if(p)open(p);});
if(typeof sectionNames!=='undefined'){sectionNames.chatapps='تطبيقات الدردشة';sectionTargets.chatapps='chatapps';}
load();
})();
