-- Base Card free Supabase schema
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null default '',
  name text not null default '',
  avatar text not null default '',
  role text not null default 'customer' check (role in ('customer','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id,email,name,avatar)
  values (new.id, coalesce(new.email,''), coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', coalesce(new.email,'')), coalesce(new.raw_user_meta_data->>'avatar_url',''))
  on conflict (id) do update set email=excluded.email, name=excluded.name, avatar=excluded.avatar, updated_at=now();
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  icon text not null default '🎮',
  description text not null default '',
  visible boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists public.packages (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games(id) on delete cascade,
  name text not null,
  price text not null,
  note text not null default '',
  visible boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique(game_id,name)
);
create table if not exists public.settings (
  key text primary key,
  value text not null default ''
);
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text unique not null,
  user_id uuid not null references public.profiles(id) on delete restrict,
  game_id bigint not null references public.games(id),
  package_id bigint not null references public.packages(id),
  player_id text not null,
  customer_name text not null,
  payment_number text not null,
  receipt_path text,
  status text not null default 'pending' check(status in ('pending','processing','completed','rejected')),
  admin_note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  name text not null,
  contact text not null,
  message text not null,
  created_at timestamptz not null default now()
);

insert into public.games(name,slug,icon,description,sort_order) values
('فري فاير','free-fire','🔥','جواهر وباقات Free Fire للاعبين الذين لا يتوقفون.',1),
('ببجي موبايل','pubg-mobile','🎯','شدات PUBG Mobile لتجهيزك للمواجهة القادمة.',2)
on conflict(slug) do nothing;
insert into public.packages(game_id,name,price,note,sort_order)
select id,'100 جوهرة','1','باقة أساسية',1 from public.games where slug='free-fire'
on conflict(game_id,name) do nothing;
insert into public.packages(game_id,name,price,note,sort_order)
select id,'530 جوهرة','5','الأكثر طلبًا',2 from public.games where slug='free-fire'
on conflict(game_id,name) do nothing;
insert into public.packages(game_id,name,price,note,sort_order)
select id,'60 شدة','1','باقة أساسية',1 from public.games where slug='pubg-mobile'
on conflict(game_id,name) do nothing;
insert into public.packages(game_id,name,price,note,sort_order)
select id,'325 شدة','5','عرض مميز',2 from public.games where slug='pubg-mobile'
on conflict(game_id,name) do nothing;
insert into public.settings(key,value) values
('site_name','Base Card'),('tagline','شحن ألعاب سريع وآمن وموثوق'),('support_whatsapp',''),('sham_cash',''),('sham_cash_qr',''),('hero_title','خلّ لعبك أقوى مع Base Card'),('hero_text','اشحن رصيدك وباقاتك المفضلة بسهولة. أسعار واضحة، تنفيذ سريع، ومتابعة حقيقية لكل طلب.'),('offer_title','اشحن أكثر، واستمتع أكثر 🎁'),('offer_text','تابع عروضنا الدورية واحصل على قيمة أفضل مع كل عملية شحن.')
on conflict(key) do nothing;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role='admin');
$$;

alter table public.profiles enable row level security;
alter table public.games enable row level security;
alter table public.packages enable row level security;
alter table public.settings enable row level security;
alter table public.orders enable row level security;
alter table public.messages enable row level security;

drop policy if exists profiles_self_or_admin on public.profiles;
create policy profiles_self_or_admin on public.profiles for select using (id=auth.uid() or public.is_admin());
drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles for update using (id=auth.uid());

drop policy if exists games_public_read on public.games;
create policy games_public_read on public.games for select using (visible=true or public.is_admin());
drop policy if exists games_admin_insert on public.games;
create policy games_admin_insert on public.games for insert with check (public.is_admin());
drop policy if exists games_admin_update on public.games;
create policy games_admin_update on public.games for update using (public.is_admin());
drop policy if exists games_admin_delete on public.games;
create policy games_admin_delete on public.games for delete using (public.is_admin());

drop policy if exists packages_public_read on public.packages;
create policy packages_public_read on public.packages for select using ((visible=true and exists(select 1 from public.games g where g.id=game_id and g.visible=true)) or public.is_admin());
drop policy if exists packages_admin_insert on public.packages;
create policy packages_admin_insert on public.packages for insert with check (public.is_admin());
drop policy if exists packages_admin_update on public.packages;
create policy packages_admin_update on public.packages for update using (public.is_admin());
drop policy if exists packages_admin_delete on public.packages;
create policy packages_admin_delete on public.packages for delete using (public.is_admin());

drop policy if exists settings_public_read on public.settings;
create policy settings_public_read on public.settings for select using (true);
drop policy if exists settings_admin_write on public.settings;
create policy settings_admin_write on public.settings for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists orders_insert_own on public.orders;
create policy orders_insert_own on public.orders for insert with check (auth.uid()=user_id);
drop policy if exists orders_read_own_or_admin on public.orders;
create policy orders_read_own_or_admin on public.orders for select using (auth.uid()=user_id or public.is_admin());
drop policy if exists orders_admin_update on public.orders;
create policy orders_admin_update on public.orders for update using (public.is_admin());

drop policy if exists messages_insert_any on public.messages;
create policy messages_insert_any on public.messages for insert with check (auth.uid()=user_id or user_id is null);
drop policy if exists messages_admin_read on public.messages;
create policy messages_admin_read on public.messages for select using (public.is_admin());

insert into storage.buckets(id,name,public) values ('receipts','receipts',true) on conflict(id) do nothing;
drop policy if exists receipts_upload_own on storage.objects;
create policy receipts_upload_own on storage.objects for insert to authenticated with check (bucket_id='receipts' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists receipts_public_read on storage.objects;
create policy receipts_public_read on storage.objects for select using (bucket_id='receipts');
