-- Base Card wallet and balance migration (run on the existing Supabase project)
create table if not exists public.wallets (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  balance_syp numeric(14,2) not null default 0 check (balance_syp >= 0),
  balance_usd numeric(14,2) not null default 0 check (balance_usd >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.wallet_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null check (type in ('topup','purchase','adjustment')),
  amount numeric(14,2) not null,
  currency text not null check (currency in ('SYP','USD')),
  balance_after numeric(14,2),
  reference_type text,
  reference_id bigint,
  description text not null default '',
  created_at timestamptz not null default now()
);
create unique index if not exists wallet_tx_reference_unique on public.wallet_transactions(reference_type, reference_id) where reference_id is not null;
create index if not exists wallet_tx_user_created on public.wallet_transactions(user_id, created_at desc);

create table if not exists public.topup_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric(14,2) not null check (amount > 0),
  currency text not null check (currency in ('SYP','USD')),
  payment_number text not null,
  receipt_path text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  admin_note text not null default '',
  reviewed_by uuid references public.profiles(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists topup_status_created on public.topup_requests(status, created_at desc);

alter table public.packages add column if not exists price_amount numeric(14,2);
alter table public.packages add column if not exists currency text not null default 'USD' check (currency in ('SYP','USD'));
update public.packages set price_amount = nullif(regexp_replace(price, '[^0-9.]', '', 'g'), '')::numeric where price_amount is null and price ~ '[0-9]';
update public.packages set price_amount = 0 where price_amount is null;

alter table public.orders alter column payment_number drop not null;
alter table public.orders add column if not exists wallet_transaction_id bigint references public.wallet_transactions(id);

insert into public.wallets(user_id)
select id from public.profiles p where not exists(select 1 from public.wallets w where w.user_id=p.id);

create or replace function public.ensure_wallet()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.wallets(user_id) values(new.id) on conflict do nothing;
  return new;
end; $$;
drop trigger if exists on_profile_wallet_created on public.profiles;
create trigger on_profile_wallet_created after insert on public.profiles for each row execute procedure public.ensure_wallet();

create or replace function public.admin_review_topup(p_request_id bigint, p_decision text, p_note text default '')
returns jsonb language plpgsql security definer set search_path=public as $$
declare r public.topup_requests; w public.wallets; new_balance numeric;
begin
  if not public.is_admin() then raise exception 'غير مصرح'; end if;
  if p_decision not in ('approved','rejected') then raise exception 'قرار غير صالح'; end if;
  select * into r from public.topup_requests where id=p_request_id for update;
  if not found then raise exception 'طلب الشحن غير موجود'; end if;
  if r.status <> 'pending' then raise exception 'تمت مراجعة الطلب سابقًا'; end if;
  if p_decision='approved' then
    insert into public.wallets(user_id) values(r.user_id) on conflict do nothing;
    select * into w from public.wallets where user_id=r.user_id for update;
    if r.currency='USD' then
      new_balance := w.balance_usd + r.amount;
      update public.wallets set balance_usd=new_balance, updated_at=now() where user_id=r.user_id;
    else
      new_balance := w.balance_syp + r.amount;
      update public.wallets set balance_syp=new_balance, updated_at=now() where user_id=r.user_id;
    end if;
    insert into public.wallet_transactions(user_id,type,amount,currency,balance_after,reference_type,reference_id,description)
    values(r.user_id,'topup',r.amount,r.currency,new_balance,'topup',r.id,'شحن رصيد عبر شام كاش');
  end if;
  update public.topup_requests set status=p_decision,admin_note=coalesce(p_note,''),reviewed_by=auth.uid(),reviewed_at=now() where id=r.id returning * into r;
  return jsonb_build_object('id',r.id,'status',r.status);
end; $$;

create or replace function public.admin_adjust_wallet(p_user_id uuid, p_amount numeric, p_currency text, p_note text default '')
returns jsonb language plpgsql security definer set search_path=public as $$
declare w public.wallets; new_balance numeric;
begin
  if not public.is_admin() then raise exception 'غير مصرح'; end if;
  if p_amount=0 or p_currency not in ('SYP','USD') then raise exception 'بيانات الرصيد غير صالحة'; end if;
  insert into public.wallets(user_id) values(p_user_id) on conflict do nothing;
  select * into w from public.wallets where user_id=p_user_id for update;
  if p_currency='USD' then
    new_balance := w.balance_usd + p_amount;
    if new_balance < 0 then raise exception 'لا يمكن أن يصبح الرصيد سالبًا'; end if;
    update public.wallets set balance_usd=new_balance,updated_at=now() where user_id=p_user_id;
  else
    new_balance := w.balance_syp + p_amount;
    if new_balance < 0 then raise exception 'لا يمكن أن يصبح الرصيد سالبًا'; end if;
    update public.wallets set balance_syp=new_balance,updated_at=now() where user_id=p_user_id;
  end if;
  insert into public.wallet_transactions(user_id,type,amount,currency,balance_after,description)
  values(p_user_id,'adjustment',p_amount,p_currency,new_balance,coalesce(p_note,'تعديل يدوي من الإدارة'));
  return jsonb_build_object('user_id',p_user_id,'balance_after',new_balance);
end; $$;

create or replace function public.purchase_with_wallet(p_game_id bigint, p_package_id bigint, p_player_id text, p_customer_name text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); pkg public.packages; w public.wallets; new_balance numeric; oid bigint; order_no text; txid bigint;
begin
  if uid is null then raise exception 'سجّل الدخول أولًا'; end if;
  if length(trim(coalesce(p_player_id,'')))=0 or length(trim(coalesce(p_customer_name,'')))=0 then raise exception 'أكمل بيانات الطلب'; end if;
  select * into pkg from public.packages where id=p_package_id and game_id=p_game_id and visible=true;
  if not found then raise exception 'الباقة غير متاحة'; end if;
  insert into public.wallets(user_id) values(uid) on conflict do nothing;
  select * into w from public.wallets where user_id=uid for update;
  if pkg.currency='USD' then
    if w.balance_usd < pkg.price_amount then raise exception 'الرصيد غير كافٍ، اشحن المحفظة أولًا'; end if;
    new_balance:=w.balance_usd-pkg.price_amount;
    update public.wallets set balance_usd=new_balance,updated_at=now() where user_id=uid;
  else
    if w.balance_syp < pkg.price_amount then raise exception 'الرصيد غير كافٍ، اشحن المحفظة أولًا'; end if;
    new_balance:=w.balance_syp-pkg.price_amount;
    update public.wallets set balance_syp=new_balance,updated_at=now() where user_id=uid;
  end if;
  order_no := 'BC-'||to_char(now(),'YYYYMMDD')||'-'||lpad((floor(random()*900000)+100000)::text,6,'0');
  insert into public.orders(order_number,user_id,game_id,package_id,player_id,customer_name,payment_number,status)
  values(order_no,uid,p_game_id,p_package_id,trim(p_player_id),trim(p_customer_name),'wallet','pending') returning id into oid;
  insert into public.wallet_transactions(user_id,type,amount,currency,balance_after,reference_type,reference_id,description)
  values(uid,'purchase',-pkg.price_amount,pkg.currency,new_balance,'order',oid,'شراء من المحفظة') returning id into txid;
  update public.orders set wallet_transaction_id=txid where id=oid;
  return jsonb_build_object('order_id',oid,'order_number',order_no,'balance_after',new_balance,'currency',pkg.currency);
end; $$;

alter table public.wallets enable row level security;
alter table public.wallet_transactions enable row level security;
alter table public.topup_requests enable row level security;
drop policy if exists wallets_self_read on public.wallets;
create policy wallets_self_read on public.wallets for select using(user_id=auth.uid() or public.is_admin());
drop policy if exists wallet_tx_self_read on public.wallet_transactions;
create policy wallet_tx_self_read on public.wallet_transactions for select using(user_id=auth.uid() or public.is_admin());
drop policy if exists topup_self_read on public.topup_requests;
create policy topup_self_read on public.topup_requests for select using(user_id=auth.uid() or public.is_admin());
drop policy if exists topup_self_insert on public.topup_requests;
create policy topup_self_insert on public.topup_requests for insert with check(user_id=auth.uid());
drop policy if exists topup_admin_update on public.topup_requests;
create policy topup_admin_update on public.topup_requests for update using(public.is_admin());

grant execute on function public.admin_review_topup(bigint,text,text) to authenticated;
grant execute on function public.admin_adjust_wallet(uuid,numeric,text,text) to authenticated;
grant execute on function public.purchase_with_wallet(bigint,bigint,text,text) to authenticated;
